### ISSUE TITLE
Bugs/redundant code

### ISSUE THREAD

**Issue by HusseinElguindi** [IdekDude/Stock-Checker#1]
The if statement's condition on line 50 of `stock.py` is faulty, it should be `if stock.status_code == 429 or stock.status_code == 403:`.

The `else: pass` on line 63 of `stock.py` is redundant.

**Comment by IdekDude** [comment]
Will fix it, or if you would like you can open a PR and fix it.

**Comment by IdekDude** [comment]
Updated it!
